# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HjNMN0yh024uJH3sWmgNGM0zewirsT6s
"""

import os
import numpy as np
import pandas as pd
import streamlit as st
from sklearn.ensemble import RandomForestClassifier

# 1. إعدادات الصفحة
st.set_page_config(
    page_title="تطبيق التنبؤ بالتعبير الجيني",
    page_icon="🧬",
    layout="centered",
)

st.title("🧬 تطبيق التنبؤ بالحالة الجينية")
st.write(
    "قم بإدخال قياسات التعبير الجيني أدناه للتنبؤ بالحالة الصحية (Control أو Treatment):"
)


# 2. دالة تحميل البيانات وتدريب النموذج
@st.cache_data
def load_and_train_model():
    base_dir = (
        os.path.dirname(os.path.abspath(__file__))
        if "__file__" in globals()
        else "."
    )

    # البحث عن ملف Excel أولاً أو ملف CSV
    excel_path = os.path.join(
        base_dir, "Human_Gene_Data_Analysis_1000_Records.xlsx"
    )
    csv_path = os.path.join(
        base_dir, "Human_Gene_Data_Analysis_1000_Records.csv"
    )

    if os.path.exists(excel_path):
        # القراءة المباشرة من ورقة Analysis_1000 داخل ملف Excel
        df = pd.read_excel(excel_path, sheet_name="Analysis_1000")
    elif os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
    else:
        raise FileNotFoundError(
            "لم يتم العثور على ملف البيانات (سواء xlsx أو csv)."
        )

    # تنظيف أسماء الأعمدة لتفادي المسافات الزائدة
    df.columns = df.columns.str.strip()

    features = [
        "Expression_Level",
        "Expression_Log2",
        "Fold_Change",
        "Significance_PValue",
    ]
    X = df[features]
    y = df["Condition"]

    # تدريب النموذج
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X, y)