# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HjNMN0yh024uJH3sWmgNGM0zewirsT6s
"""

import os
import numpy as np
import pandas as pd
import streamlit as st
from sklearn.ensemble import RandomForestClassifier

# 1. إعدادات الصفحة
st.set_page_config(
    page_title="تطبيق التنبؤ بالتعبير الجيني",
    page_icon="🧬",
    layout="centered",
)

st.title("🧬 تطبيق التنبؤ بالحالة الجينية")
st.write(
    "قم بإدخال قياسات التعبير الجيني أدناه للتنبؤ بالحالة الصحية (Control أو Treatment):"
)


# 2. دالة تحميل البيانات وتدريب النموذج
@st.cache_data
def load_and_train_model():
    base_dir = (
        os.path.dirname(os.path.abspath(__file__))
        if "__file__" in globals()
        else "."
    )

    excel_path = os.path.join(
        base_dir, "Human_Gene_Data_Analysis_1000_Records.xlsx"
    )
    csv_path = os.path.join(
        base_dir, "Human_Gene_Data_Analysis_1000_Records.csv"
    )

    if os.path.exists(excel_path):
        df = pd.read_excel(excel_path, sheet_name="Analysis_1000")
    elif os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
    else:
        raise FileNotFoundError(
            "لم يتم العثور على ملف البيانات (سواء xlsx أو csv)."
        )

    df.columns = df.columns.str.strip()

    features = [
        "Expression_Level",
        "Expression_Log2",
        "Fold_Change",
        "Significance_PValue",
    ]
    X = df[features]
    y = df["Condition"]

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X, y)
    return model


# 3. تحميل النموذج
try:
    model = load_and_train_model()
except Exception as e:
    st.error(f"تعذر تحميل الملف أو تدريب النموذج. التفاصيل: {e}")
    st.stop()

# 4. خانات الإدخال في منتصف الصفحة مباشرة (Main Page)
st.subheader("🎛️ أدخل قياسات الجين:")

col1, col2 = st.columns(2)

with col1:
    expression_level = st.number_input(
        "Expression Level", value=500.0, step=10.0
    )
    fold_change = st.number_input("Fold Change", value=1.5, step=0.1)

with col2:
    expression_log2 = st.number_input("Expression Log2", value=8.0, step=0.1)
    p_value = st.number_input(
        "Significance P-Value", value=0.01, step=0.001, format="%.6f"
    )

# 5. زر التنبؤ والنتائج
if st.button("🚀 إجراء التنبؤ", use_container_width=True):
    input_data = pd.DataFrame(
        [[expression_level, expression_log2, fold_change, p_value]],
        columns=[
            "Expression_Level",
            "Expression_Log2",
            "Fold_Change",
            "Significance_PValue",
        ],
    )

    prediction = model.predict(input_data)[0]
    probabilities = model.predict_proba(input_data)[0]
    confidence = np.max(probabilities) * 100

    st.markdown("---")
    st.subheader("📊 نتيجة التنبؤ:")

    if prediction == "Control":
        st.info(f"الحالة المتوقعة: **{prediction}**")
    else:
        st.warning(f"الحالة المتوقعة: **{prediction}**")

    st.write(f"نسبة الثقة في التنبؤ: **{confidence:.2f}%**")