# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HjNMN0yh024uJH3sWmgNGM0zewirsT6s
"""

import os
import numpy as np
import pandas as pd
import streamlit as st
from sklearn.ensemble import RandomForestClassifier

# 1. إعدادات الصفحة والعنوان
st.set_page_config(
    page_title="تطبيق التنبؤ بالتعبير الجيني",
    page_icon="🧬",
    layout="centered",
)

st.title("🧬 تطبيق التنبؤ بالحالة الجينية")
st.write(
    "قم بإدخال قياسات التعبير الجيني أدناه للتنبؤ بالحالة الصحية (Control أو Treatment):"
)


# 2. دالة تحميل البيانات وتدريب النموذج
@st.cache_data
def load_and_train_model():
    # التحقق من وجود المتغير __file__ لتحديد المسار بحسب بيئة التشغيل
    if "__file__" in globals():
        base_dir = os.path.dirname(os.path.abspath(__file__))
        file_path = os.path.join(
            base_dir, "Human_Gene_Data_Analysis_1000_Records.csv"
        )
    else:
        file_path = "Human_Gene_Data_Analysis_1000_Records.csv"

    # قراءة ملف البيانات
    df = pd.read_csv(file_path)

    # تحديد الميزات والهدف
    features = [
        "Expression_Level",
        "Expression_Log2",
        "Fold_Change",
        "Significance_PValue",
    ]
    X = df[features]
    y = df["Condition"]

    # تدريب النموذج
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X, y)
    return model


# 3. تحميل النموذج
try:
    model = load_and_train_model()
except Exception as e:
    st.error(
        f"تعذر تحميل الملف أو تدريب النموذج. تأكد من وجود ملف CSV بنفس الاسم. الخطأ: {e}"
    )
    st.stop()

# 4. القائمة الجانبية لإدخال قيم الميزات (Sidebar)
st.sidebar.header("🎛️ أدخل قياسات الجين")

expression_level = st.sidebar.number_input(
    "Expression Level", value=500.0, step=10.0
)
expression_log2 = st.sidebar.number_input(
    "Expression Log2", value=8.0, step=0.1
)
fold_change = st.sidebar.number_input("Fold Change", value=1.5, step=0.1)
p_value = st.sidebar.number_input(
    "Significance P-Value", value=0.01, step=0.001, format="%.6f"
)

# 5. التنبؤ وعرض النتائج
if st.button("🚀 إجراء التنبؤ"):
    input_data = pd.DataFrame(
        [[expression_level, expression_log2, fold_change, p_value]],
        columns=[
            "Expression_Level",
            "Expression_Log2",
            "Fold_Change",
            "Significance_PValue",
        ],
    )

    prediction = model.predict(input_data)[0]
    probabilities = model.predict_proba(input_data)[0]
    confidence = np.max(probabilities) * 100

    st.markdown("---")
    st.subheader("📊 نتيجة التنبؤ:")

    if prediction == "Control":
        st.info(f"الحالة المتوقعة: **{prediction}**")
    else:
        st.warning(f"الحالة المتوقعة: **{prediction}**")

    st.write(f"نسبة الثقة في التنبؤ: **{confidence:.2f}%**")